language: node_js
node_js:
  - "8"
install:
  - npm install
script:
  - npm test
  - npm run package
before_deploy:
  - for f in package/*.zip; do mv "$f" "`echo $f | sed s/.zip/_$TRAVIS_COMMIT.zip/`"; done # Append commit to package file
deploy:
  provider: bintray
  file: ".deploy/bintray.json"
  user: $BINTRAY_USERNAME
  key: $BINTRAY_API_KEY
  on:
    branch: develop
branches:
  only:
  - master
  - develop
