language: node_js
node_js:
  - "8"
install:
  - npm install
script:
  - npm test
  - npm run package
before_deploy:
  - node -e "const fs = require('fs');const bintray = require('./bintray.json');bintray.version.name = \"$TRAVIS_BRANCH\";bintray.version.desc = \"$TRAVIS_COMMIT\";fs.writeFileSync('./bintray.json', JSON.stringify(bintray), 'utf8');"
deploy:
  provider: bintray
  file: "bintray.json"
  user: $BINTRAY_USERNAME
  key: $BINTRAY_API_KEY
  on:
 	condition: $TRAVIS_BRANCH == "master" || $TRAVIS_BRANCH == "develop"
branches:
  only:
  - master
  - develop
