language: node_js
node_js:
  - "8"
install:
  - npm install
script:
  - npm test
  - npm run package
before_deploy:
  - SHA01=$(echo $TRAVIS_COMMIT | cut -c1-8) # Find commit sha01
  - for f in package/*.zip; do mv "$f" "`echo $f | sed s/.zip/.$SHA01.$TRAVIS_BRANCH.zip/`"; done
  - ARTIFACT_FILENAME=package/$(ls package | grep .zip)
deploy:
  - curl -u $BITBUCKET_USERNAME:$BITBUCKET_PASSWORD -X POST https://api.bitbucket.org/2.0/repositories/thomaschampagne/stravistix-ci-builds/downloads --form files=@$ARTIFACT_FILENAME
branches:
  only:
  - master
  - develop
